name: 'Build and Push Docker Container'
description: 'Build and push Docker container to registry'

inputs:
  app-name:
    description: 'Application name for Docker image'
    required: true
  docker-token:
    description: 'Docker registry token'
    required: true
  repository-owner:
    description: 'Repository owner for Docker image'
    required: true
  platforms:
    description: 'Target platforms for Docker build'
    required: false
    default: 'linux/amd64,linux/arm64,linux/arm'
  push:
    description: 'Whether to push the image'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: docker/setup-qemu-action@v3
    
    - uses: docker/setup-buildx-action@v3
    
    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.repository-owner }}
        password: ${{ inputs.docker-token }}
    
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.repository-owner }}/${{ inputs.app-name }}
    
    - uses: docker/build-push-action@v6
      with:
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}