// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: EndpointEncryptor,EndpointDecryptor)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_endpoint.go -package=mock_ctrl . EndpointEncryptor,EndpointDecryptor
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	context "context"
	reflect "reflect"

	ctrl "github.com/tjjh89017/stunmesh-go/internal/ctrl"
	gomock "go.uber.org/mock/gomock"
)

// MockEndpointEncryptor is a mock of EndpointEncryptor interface.
type MockEndpointEncryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointEncryptorMockRecorder
	isgomock struct{}
}

// MockEndpointEncryptorMockRecorder is the mock recorder for MockEndpointEncryptor.
type MockEndpointEncryptorMockRecorder struct {
	mock *MockEndpointEncryptor
}

// NewMockEndpointEncryptor creates a new mock instance.
func NewMockEndpointEncryptor(ctrl *gomock.Controller) *MockEndpointEncryptor {
	mock := &MockEndpointEncryptor{ctrl: ctrl}
	mock.recorder = &MockEndpointEncryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointEncryptor) EXPECT() *MockEndpointEncryptorMockRecorder {
	return m.recorder
}

// Encrypt mocks base method.
func (m *MockEndpointEncryptor) Encrypt(ctx context.Context, input *ctrl.EndpointEncryptRequest) (*ctrl.EndpointEncryptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", ctx, input)
	ret0, _ := ret[0].(*ctrl.EndpointEncryptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEndpointEncryptorMockRecorder) Encrypt(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEndpointEncryptor)(nil).Encrypt), ctx, input)
}

// MockEndpointDecryptor is a mock of EndpointDecryptor interface.
type MockEndpointDecryptor struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointDecryptorMockRecorder
	isgomock struct{}
}

// MockEndpointDecryptorMockRecorder is the mock recorder for MockEndpointDecryptor.
type MockEndpointDecryptorMockRecorder struct {
	mock *MockEndpointDecryptor
}

// NewMockEndpointDecryptor creates a new mock instance.
func NewMockEndpointDecryptor(ctrl *gomock.Controller) *MockEndpointDecryptor {
	mock := &MockEndpointDecryptor{ctrl: ctrl}
	mock.recorder = &MockEndpointDecryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointDecryptor) EXPECT() *MockEndpointDecryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEndpointDecryptor) Decrypt(ctx context.Context, input *ctrl.EndpointDecryptRequest) (*ctrl.EndpointDecryptResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ctx, input)
	ret0, _ := ret[0].(*ctrl.EndpointDecryptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEndpointDecryptorMockRecorder) Decrypt(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEndpointDecryptor)(nil).Decrypt), ctx, input)
}
