// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: Publisher,Establisher)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_ping_targets.go -package=mock_ctrl . Publisher,Establisher
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	reflect "reflect"

	entity "github.com/tjjh89017/stunmesh-go/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// TriggerForPeer mocks base method.
func (m *MockPublisher) TriggerForPeer(peerId entity.PeerId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerForPeer", peerId)
}

// TriggerForPeer indicates an expected call of TriggerForPeer.
func (mr *MockPublisherMockRecorder) TriggerForPeer(peerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerForPeer", reflect.TypeOf((*MockPublisher)(nil).TriggerForPeer), peerId)
}

// MockEstablisher is a mock of Establisher interface.
type MockEstablisher struct {
	ctrl     *gomock.Controller
	recorder *MockEstablisherMockRecorder
	isgomock struct{}
}

// MockEstablisherMockRecorder is the mock recorder for MockEstablisher.
type MockEstablisherMockRecorder struct {
	mock *MockEstablisher
}

// NewMockEstablisher creates a new mock instance.
func NewMockEstablisher(ctrl *gomock.Controller) *MockEstablisher {
	mock := &MockEstablisher{ctrl: ctrl}
	mock.recorder = &MockEstablisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEstablisher) EXPECT() *MockEstablisherMockRecorder {
	return m.recorder
}

// TriggerForPeer mocks base method.
func (m *MockEstablisher) TriggerForPeer(peerId entity.PeerId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerForPeer", peerId)
}

// TriggerForPeer indicates an expected call of TriggerForPeer.
func (mr *MockEstablisherMockRecorder) TriggerForPeer(peerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerForPeer", reflect.TypeOf((*MockEstablisher)(nil).TriggerForPeer), peerId)
}
