// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: WireGuardClient)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_api.go -package=mock_ctrl . WireGuardClient
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	reflect "reflect"

	wg "github.com/tjjh89017/stunmesh-go/internal/wg"
	gomock "go.uber.org/mock/gomock"
)

// MockWireGuardClient is a mock of WireGuardClient interface.
type MockWireGuardClient struct {
	ctrl     *gomock.Controller
	recorder *MockWireGuardClientMockRecorder
	isgomock struct{}
}

// MockWireGuardClientMockRecorder is the mock recorder for MockWireGuardClient.
type MockWireGuardClientMockRecorder struct {
	mock *MockWireGuardClient
}

// NewMockWireGuardClient creates a new mock instance.
func NewMockWireGuardClient(ctrl *gomock.Controller) *MockWireGuardClient {
	mock := &MockWireGuardClient{ctrl: ctrl}
	mock.recorder = &MockWireGuardClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWireGuardClient) EXPECT() *MockWireGuardClientMockRecorder {
	return m.recorder
}

// Device mocks base method.
func (m *MockWireGuardClient) Device(deviceName string) (*wg.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Device", deviceName)
	ret0, _ := ret[0].(*wg.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Device indicates an expected call of Device.
func (mr *MockWireGuardClientMockRecorder) Device(deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Device", reflect.TypeOf((*MockWireGuardClient)(nil).Device), deviceName)
}

// UpdatePeerEndpoint mocks base method.
func (m *MockWireGuardClient) UpdatePeerEndpoint(u wg.PeerEndpointUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePeerEndpoint", u)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePeerEndpoint indicates an expected call of UpdatePeerEndpoint.
func (mr *MockWireGuardClientMockRecorder) UpdatePeerEndpoint(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePeerEndpoint", reflect.TypeOf((*MockWireGuardClient)(nil).UpdatePeerEndpoint), u)
}
