// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: DeviceConfigProvider)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_device_config.go -package=mock_ctrl . DeviceConfigProvider
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDeviceConfigProvider is a mock of DeviceConfigProvider interface.
type MockDeviceConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceConfigProviderMockRecorder
	isgomock struct{}
}

// MockDeviceConfigProviderMockRecorder is the mock recorder for MockDeviceConfigProvider.
type MockDeviceConfigProviderMockRecorder struct {
	mock *MockDeviceConfigProvider
}

// NewMockDeviceConfigProvider creates a new mock instance.
func NewMockDeviceConfigProvider(ctrl *gomock.Controller) *MockDeviceConfigProvider {
	mock := &MockDeviceConfigProvider{ctrl: ctrl}
	mock.recorder = &MockDeviceConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceConfigProvider) EXPECT() *MockDeviceConfigProviderMockRecorder {
	return m.recorder
}

// GetInterfaceProtocol mocks base method.
func (m *MockDeviceConfigProvider) GetInterfaceProtocol(deviceName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterfaceProtocol", deviceName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInterfaceProtocol indicates an expected call of GetInterfaceProtocol.
func (mr *MockDeviceConfigProviderMockRecorder) GetInterfaceProtocol(deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceProtocol", reflect.TypeOf((*MockDeviceConfigProvider)(nil).GetInterfaceProtocol), deviceName)
}

// GetProxyFib mocks base method.
func (m *MockDeviceConfigProvider) GetProxyFib(deviceName string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxyFib", deviceName)
	ret0, _ := ret[0].(int)
	return ret0
}

// GetProxyFib indicates an expected call of GetProxyFib.
func (mr *MockDeviceConfigProviderMockRecorder) GetProxyFib(deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxyFib", reflect.TypeOf((*MockDeviceConfigProvider)(nil).GetProxyFib), deviceName)
}

// TunnelInterfaceNames mocks base method.
func (m *MockDeviceConfigProvider) TunnelInterfaceNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TunnelInterfaceNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// TunnelInterfaceNames indicates an expected call of TunnelInterfaceNames.
func (mr *MockDeviceConfigProviderMockRecorder) TunnelInterfaceNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TunnelInterfaceNames", reflect.TypeOf((*MockDeviceConfigProvider)(nil).TunnelInterfaceNames))
}
