// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: PluginProvider)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_plugin_provider.go -package=mock_ctrl . PluginProvider
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	reflect "reflect"

	pluginapi "github.com/tjjh89017/stunmesh-go/pluginapi"
	gomock "go.uber.org/mock/gomock"
)

// MockPluginProvider is a mock of PluginProvider interface.
type MockPluginProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPluginProviderMockRecorder
	isgomock struct{}
}

// MockPluginProviderMockRecorder is the mock recorder for MockPluginProvider.
type MockPluginProviderMockRecorder struct {
	mock *MockPluginProvider
}

// NewMockPluginProvider creates a new mock instance.
func NewMockPluginProvider(ctrl *gomock.Controller) *MockPluginProvider {
	mock := &MockPluginProvider{ctrl: ctrl}
	mock.recorder = &MockPluginProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginProvider) EXPECT() *MockPluginProviderMockRecorder {
	return m.recorder
}

// GetPlugin mocks base method.
func (m *MockPluginProvider) GetPlugin(name string) (pluginapi.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlugin", name)
	ret0, _ := ret[0].(pluginapi.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlugin indicates an expected call of GetPlugin.
func (mr *MockPluginProviderMockRecorder) GetPlugin(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlugin", reflect.TypeOf((*MockPluginProvider)(nil).GetPlugin), name)
}

// IsDedup mocks base method.
func (m *MockPluginProvider) IsDedup(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDedup", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDedup indicates an expected call of IsDedup.
func (mr *MockPluginProviderMockRecorder) IsDedup(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDedup", reflect.TypeOf((*MockPluginProvider)(nil).IsDedup), name)
}
