// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: StunResolver)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_stun.go -package=mock_ctrl . StunResolver
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStunResolver is a mock of StunResolver interface.
type MockStunResolver struct {
	ctrl     *gomock.Controller
	recorder *MockStunResolverMockRecorder
	isgomock struct{}
}

// MockStunResolverMockRecorder is the mock recorder for MockStunResolver.
type MockStunResolverMockRecorder struct {
	mock *MockStunResolver
}

// NewMockStunResolver creates a new mock instance.
func NewMockStunResolver(ctrl *gomock.Controller) *MockStunResolver {
	mock := &MockStunResolver{ctrl: ctrl}
	mock.recorder = &MockStunResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStunResolver) EXPECT() *MockStunResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockStunResolver) Resolve(ctx context.Context, deviceName string, port uint16, protocol string) (string, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, deviceName, port, protocol)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resolve indicates an expected call of Resolve.
func (mr *MockStunResolverMockRecorder) Resolve(ctx, deviceName, port, protocol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockStunResolver)(nil).Resolve), ctx, deviceName, port, protocol)
}
