// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tjjh89017/stunmesh-go/internal/ctrl (interfaces: WireGuardClient,ICMPConnection)
//
// Generated by this command:
//
//	mockgen -destination=./mock/mock_api.go -package=mock_ctrl . WireGuardClient,ICMPConnection
//

// Package mock_ctrl is a generated GoMock package.
package mock_ctrl

import (
	net "net"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	wgtypes "golang.zx2c4.com/wireguard/wgctrl/wgtypes"
)

// MockWireGuardClient is a mock of WireGuardClient interface.
type MockWireGuardClient struct {
	ctrl     *gomock.Controller
	recorder *MockWireGuardClientMockRecorder
	isgomock struct{}
}

// MockWireGuardClientMockRecorder is the mock recorder for MockWireGuardClient.
type MockWireGuardClientMockRecorder struct {
	mock *MockWireGuardClient
}

// NewMockWireGuardClient creates a new mock instance.
func NewMockWireGuardClient(ctrl *gomock.Controller) *MockWireGuardClient {
	mock := &MockWireGuardClient{ctrl: ctrl}
	mock.recorder = &MockWireGuardClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWireGuardClient) EXPECT() *MockWireGuardClientMockRecorder {
	return m.recorder
}

// ConfigureDevice mocks base method.
func (m *MockWireGuardClient) ConfigureDevice(deviceName string, cfg wgtypes.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfigureDevice", deviceName, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfigureDevice indicates an expected call of ConfigureDevice.
func (mr *MockWireGuardClientMockRecorder) ConfigureDevice(deviceName, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfigureDevice", reflect.TypeOf((*MockWireGuardClient)(nil).ConfigureDevice), deviceName, cfg)
}

// Device mocks base method.
func (m *MockWireGuardClient) Device(deviceName string) (*wgtypes.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Device", deviceName)
	ret0, _ := ret[0].(*wgtypes.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Device indicates an expected call of Device.
func (mr *MockWireGuardClientMockRecorder) Device(deviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Device", reflect.TypeOf((*MockWireGuardClient)(nil).Device), deviceName)
}

// MockICMPConnection is a mock of ICMPConnection interface.
type MockICMPConnection struct {
	ctrl     *gomock.Controller
	recorder *MockICMPConnectionMockRecorder
	isgomock struct{}
}

// MockICMPConnectionMockRecorder is the mock recorder for MockICMPConnection.
type MockICMPConnectionMockRecorder struct {
	mock *MockICMPConnection
}

// NewMockICMPConnection creates a new mock instance.
func NewMockICMPConnection(ctrl *gomock.Controller) *MockICMPConnection {
	mock := &MockICMPConnection{ctrl: ctrl}
	mock.recorder = &MockICMPConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICMPConnection) EXPECT() *MockICMPConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockICMPConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockICMPConnectionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockICMPConnection)(nil).Close))
}

// Recv mocks base method.
func (m *MockICMPConnection) Recv(buffer []byte, timeout time.Duration) (int, net.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv", buffer, timeout)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(net.Addr)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Recv indicates an expected call of Recv.
func (mr *MockICMPConnectionMockRecorder) Recv(buffer, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockICMPConnection)(nil).Recv), buffer, timeout)
}

// Send mocks base method.
func (m *MockICMPConnection) Send(data []byte, addr net.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", data, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockICMPConnectionMockRecorder) Send(data, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockICMPConnection)(nil).Send), data, addr)
}

// SetReadDeadline mocks base method.
func (m *MockICMPConnection) SetReadDeadline(t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReadDeadline", t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetReadDeadline indicates an expected call of SetReadDeadline.
func (mr *MockICMPConnectionMockRecorder) SetReadDeadline(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReadDeadline", reflect.TypeOf((*MockICMPConnection)(nil).SetReadDeadline), t)
}
