// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/rs/zerolog"
	"github.com/tjjh89017/stunmesh-go/internal/config"
	"github.com/tjjh89017/stunmesh-go/internal/crypto"
	"github.com/tjjh89017/stunmesh-go/internal/ctrl"
	"github.com/tjjh89017/stunmesh-go/internal/daemon"
	"github.com/tjjh89017/stunmesh-go/internal/entity"
	"github.com/tjjh89017/stunmesh-go/internal/logger"
	"github.com/tjjh89017/stunmesh-go/internal/plugin"
	"github.com/tjjh89017/stunmesh-go/internal/repo"
)

// Injectors from wire.go:

func setup(cfg *config.Config) (*daemon.Daemon, func(), error) {
	deviceConfig := config.NewDeviceConfig(cfg)
	zerologLogger := logger.NewLogger(cfg)
	appProxyStack, cleanup, err := newProxyStack(cfg, deviceConfig, zerologLogger)
	if err != nil {
		return nil, nil, err
	}
	client := appProxyStack.Client
	devices := repo.NewDevices()
	peers := repo.NewPeers(client)
	filterPeerService := entity.NewFilterPeerService(peers, deviceConfig)
	bootstrapController := ctrl.NewBootstrapController(client, cfg, deviceConfig, devices, peers, zerologLogger, filterPeerService)
	manager, cleanup2, err := providePluginManager(cfg, zerologLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	resolver := appProxyStack.Resolver
	endpoint := crypto.NewEndpoint()
	publishController := ctrl.NewPublishController(devices, peers, manager, resolver, endpoint, deviceConfig, zerologLogger)
	establishController := ctrl.NewEstablishController(client, devices, peers, manager, endpoint, deviceConfig, zerologLogger)
	pingMonitorController := ctrl.NewPingMonitorController(cfg, devices, peers, publishController, establishController, zerologLogger)
	daemonDaemon := daemon.New(cfg, bootstrapController, publishController, establishController, pingMonitorController, zerologLogger)
	return daemonDaemon, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func providePluginManager(config2 *config.Config, logger2 *zerolog.Logger) (*plugin.Manager, func(), error) {
	manager := plugin.NewManager()
	ctx := context.Background()

	if err := manager.LoadPlugins(ctx, config2.Plugins); err != nil {
		return nil, nil, err
	}

	cleanup := func() {
		if err := manager.Close(); err != nil {
			logger2.
				Warn().Err(err).Msg("failed to close plugin manager")
		}
	}

	return manager, cleanup, nil
}
